style_edition = "2024"
edition = "2024"
unstable_features = true
reorder_impl_items = true
wrap_comments = true
use_field_init_shorthand = true
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true
imports_granularity = "Module"
imports_layout = "HorizontalVertical"
merge_derives = true
use_small_heuristics = "Default"
